# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-d1cIArQrqd5sS3r6UwXNn1yh3_3tuop
"""

import streamlit as st
from langchain_community.document_loaders import DirectoryLoader, PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_groq import ChatGroq
from dotenv import load_dotenv
import os
@st.cache_resource
def load_and_prepare():
    loader = DirectoryLoader("data", glob="*.pdf", loader_cls=PyPDFLoader)
    docs = loader.load()
    splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
    chunks = splitter.split_documents(docs)
    embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
    vectorstore = FAISS.from_documents(chunks, embedding)
    return vectorstore

vectorstore = load_and_prepare()
retriever = vectorstore.as_retriever(search_kwargs={"k": 3})st.sidebar.title("Model Settings")
model_name = "llama-3.3-70b-versatile"
temperature = st.sidebar.slider("Temperature", 0.0, 1.0, 0.0)
st.sidebar.write(f"Model: {model_name}")st.title("RAG Chatbot")
user_question = st.text_input("Ask a sales-related question:")
if st.button("Get Answer"):
    if user_question:
        retrieved_docs = retriever.invoke(user_question)
        context = "\n\n".join(doc.page_content for doc in retrieved_docs)
        prompt = f"{SYSTEM_PROMPT}\n\nRetrieved Context:\n{context}\n\nUser Question:\n{user_question}\n\nRespond accordingly."
        llm = ChatGroq(api_key=os.getenv("GROQ_API_KEY"), model=model_name, temperature=temperature)
        response = llm.invoke(prompt)
        st.write("Answer:")
        st.write(response.content)